### ISSUE TITLE
Alert fails on dashboard using opensearch datasource with TLS client auth enabled

### ISSUE THREAD

**Issue by devesh2k7** [grafana/opensearch-datasource#111]
When testing an alert created using Opensearch as datasource for a dashboard panel, we get an error that occurs while testing the alert rule that is configured:

**tsdb.HandleRequest() error rpc error: code = Unknown desc = invalid character 'U' looking for beginning of value**

![image](https://user-images.githubusercontent.com/39185310/225708206-42b1d135-73dd-4da7-84ff-f9bcaee4cd8a.png)

We have configured the Opensearch datasource used in Grafana as below.

datasources:
    - name: opensearch-ds
      type: grafana-opensearch-datasource
      version: 2
      access: proxy
      orgId: 1
      url: {{ .Values.opensearch.url }}
      jsonData:
        interval: Daily
        timeField: "@timestamp"
        timeInterval: "10m"
        tlsAuth: true
        tlsAuthWithCACert: true
        database: "[opensearch-ds-]YYYY.MM.DD"
        version: "1.0.0"
        tlsSkipVerify: true
      secureJsonData:
        tlsCACert: $ENV_VAR_1
        tlsClientCert: $ENV_VAR_2
        tlsClientKey: $ENV_VAR_3

![image](https://user-images.githubusercontent.com/39185310/225709544-4a1236ba-8bde-44f1-963b-0beecdcfd1c6.png)

Please help us in getting this issue fixed at the earliest.

Grafana version: 7.5.17
Opensearch Datasource Plugin version: 1.1.2
Opensearch version: 2.4.1

**Note:** The alert does not work and it fails with same error even with the latest Grafana version 9.3.6 and the latest Opensearch datasource plugin version 2.0.5. 

Please note although that we want the fix for the older version of Grafana (v7.5.17) and Opensearch datasource plugin (v1.1.2) as mentioned above in the issue description.

**Comment by sarahzinger** [comment]
@devesh2k7 thanks for that! A few more clarifying questions for when you get a chance:

- do you know if this error only happens when TLS is enabled? 
- do queries load successfully and it's just alerting that fails?
- do you get the same error for any kind of opensearch alert that you're trying to make or is it limited to a particular query?
- did this used to work for you at some point and suddenly stop working? (ex after upgrading something?)

and to clarify are these the versions you're seeing the issue on?
opensearch 1.2 https://opensearch.org/docs/1.2/
with the grafana opensearch plugin on 2.1.0 https://github.com/grafana/opensearch-datasource/releases/tag/v2.1.0
and grafana 9.3.6 https://github.com/grafana/grafana/releases/tag/v9.3.6

**Comment by fridgepoet** [comment]
Hi @devesh2k7, thanks for all the responses.

* What was your exact process to trigger the error in 9.3.6, please?
* Do you know if the error will occur when you use basic auth as well?

**Comment by fridgepoet** [comment]
Hi @devesh2k7 thanks for reporting this issue and providing all the information!
I believe the keys and certificates were not being transferred in the alert queries. The fix should be in the next release (estimated this week).
