### ISSUE TITLE
Automatic Version detection sometimes gets Elasticsearch 7.10.2 for Opensearch

### ISSUE THREAD

**Issue by iwysiu** [grafana/opensearch-datasource#206]
Some users are reporting that when they use the `Save and Set Version` button in the config page, the version that is found is Elasticsearch 7.10.2 despite being on Opensearch.

After investigating, I found that when this was happening the Opensearch instance was responding to the version request with the response for an Elasticsearch 7.10.2. I haven't confirmed it, but I believe that this happens because the instance has [compatibility mode enabled](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createupdatedomains.html#:~:text=Enable%20compatibility%20mode), which "make[s] OpenSearch report its version as 7.10, which allows certain Elasticsearch OSS clients and plugins that check the version before connecting to continue working with the service."

The solution for this would probably be for OpenSearch to provide a different endpoint that we could check to get the actual version, or to go back to users setting the version itself.

(Alternatively we change the message to just confirm that the version was fetched and not display it. We should double check but I don't think we actually build queries differently for 7.10 and OpenSearch)

**Comment by sarahzinger** [comment]
Moving this to waiting, while we get input from AWS on this

**Comment by hackery** [comment]
For some additional context: I encountered this problem a couple of months ago with AWS OpenSearch, with Grafana [mis-identifying is as Elasticsearch 7.10.2](https://github.com/grafana/opensearch-datasource/blob/main/src/opensearchDatasource.ts#L784) because the cluster identification output omitted the `distribution` field, and finding that was because of (in)compatibility mode.

In this AWS doc [Get started: Upgrade your domains to OpenSearch 1.x](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html#rename-upgrade) it says (my emphasis added):

> You can enable compatibility mode when you create OpenSearch domains for the first time, or when you upgrade to OpenSearch from an Elasticsearch version. If it's not set, the parameter *defaults to false when you create a domain, and true when you upgrade a domain*.

We had indeed upgraded our domains, but between OpenSearch versions - we never had Elasticsearch in our AWS accounts. This suggests to me that AWS have mistakenly set this compatibility flag on *all* upgrades, not just ES->OS.

I did also see places in the Grafana datasource code where the query builder seemed to perform aggregations differently depending on flavor/version, but couldn't find anything matching the specific problem I'd seen (exceeding aggs bucket counts).

**Comment by iwysiu** [comment]
Hi @hackery ! Are you still seeing this problem? As of version [2.17.1](https://github.com/grafana/opensearch-datasource/releases/tag/v2.17.1) of the plugin it should be able to tell the difference between Elasticsearch and Compatibility mode OpenSearch. If the issue is how OpenSearch is setting the compatibility flag, you'll have to file that with AWS.

**Comment by hackery** [comment]
We're currently on Grafana 10.2.3 and plugin 2.16.1.

We have a support request in with AWS about this already, but I'll look at getting the plugin updated.
