### ISSUE TITLE
Not reading Data-Field Type in rawData Query after version 2.16.0

### ISSUE THREAD

**Issue by SebastianOpeni** [grafana/opensearch-datasource#420]
Hello together,

i noticed a problem with newer versions of the plugin:

Graph working with plugin version 2.16.0:
![2_16_0_graph](https://github.com/grafana/opensearch-datasource/assets/166400577/40d4c4da-00ed-4dee-bf80-2bada62ada38)

Graph not working with plugin version 2.16.1:
![2_16_1_graph](https://github.com/grafana/opensearch-datasource/assets/166400577/3b5c688a-1ac0-4987-a1bd-be6da1f1a81a)

**What happened**:
After Upgrading to a Version greater than 2.16.0. (I tested 2.16.1,2.17.0) the graph can not be plotted anymore because for the raw_data Query gafana does not know weather a field is a number or not anymore.

**What you expected to happen**:
It still can read the Data-Type and therefore plot my graph.

**How to reproduce it (as minimally and precisely as possible)**:
I draw a "Raw data" Graphs of my Dataset in plugin-version 2.16.0.
And then I upgrade the plugin to 2.16.1 or 2.17.0.

**Anything else we need to know?**:

You can get it to work again by converting the field-types via grafana transformations, but this has to be done for every field => that would defeat the purpose of "Raw Data".
By downgrading the plugin to version 1.16.0 the type-detection works again.

**Environment**:
- Grafana version: 11.0.1
- OpenSearch version: 2.15.0
- Plugin version: 1.16.1 and 1.17.0

I hope I provided enough information about the issue.
If not please feel free to ask.
Thank you for your time.

Best regards,
Sebastian

**Comment by sarahzinger** [comment]
Hi @SebastianOpeni,

Thank you for the very detailed bug report! I am able to recreate on my end: 

- On v2.16.0 I create a dashboard panel that renders raw data in a time series and save
- then I upgrade to 2.16.1 and view that dashboard panel and it doesn't detect the time field. 

This seems related to our recent refactoring in which we make all queries and format data frames on the backend instead of on the frontend of this plugin. I think we had an oversight in our logic here where we had previously been running queries through the new flow, and then decided to put that work behind a feature flag, not realizing not everyone would have that feature flag just yet (and that there was a bug in the difference between the new). 

If you're using a grafana cloud account, you should see this change get fixed when your grafana version is 11.2 or greater.

Or if you're on a self-hosted grafana instance, you can fix this by adding a [configuration flag for a feature toggle](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/) for `openSearchBackendFlowEnabled = true`, or you can keep using 2.16.0 until Grafana 11.2 is released and then can upgrade both the plugin and grafana. 

Hope that helps, sorry for any confusion! Let us know if any of those workarounds don't work for you!

**Comment by SebastianOpeni** [comment]
Thank you @sarahzinger ,

i beforehand analyzed the small code changes between the versions and suspected something like that, but did simply not know about the feature toggle.
Maybe it would make sense to add a sentence or two to the plugins readme.

After configuring the toggle in the grafana.ini it was indeed possible to upgrade the plugin without breaking the dashboards :)

Best regards,

**Comment by sarahzinger** [comment]
We will be more diligent about updating documentation in the future! Since you are unblocked, we are going to close this issue! Thanks again for reporting!
